// frontend/src/components/NavBar.vue
<template>
  <nav class="bg-white shadow-lg sticky top-0 z-50">
    <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
      <div class="flex h-16 justify-between items-center">
        <!-- Logo and brand -->
        <div class="flex items-center">
          <router-link to="/" class="flex items-center space-x-3">
            <!-- Custom Logo -->
            <img :src="logo" alt="GDPR Processor Logo"
              class="h-16 w-auto transition-transform duration-200 hover:scale-105" @error="useFallbackLogo = true"
              v-if="!useFallbackLogo" />
            <!-- Fallback Logo -->
            <div v-else class="h-14 w-10 rounded-full bg-indigo-600 flex items-center justify-center">
              <span class="text-white font-bold">G</span>
            </div>
            <span class="text-lg font-bold text-gray-900 tracking-tight">GDPR Processor</span>
          </router-link>
        </div>

        <!-- Main navigation - Desktop -->
        <div class="hidden sm:ml-6 sm:flex sm:items-center">
          <div class="flex space-x-1">
            <router-link v-for="item in navigationItems" :key="item.name" :to="item.href" :class="[
              isActive(item.href)
                ? 'bg-indigo-100 text-indigo-700'
                : 'text-gray-600 hover:bg-indigo-50 hover:text-indigo-700',
              'px-4 py-2 rounded-lg text-sm font-medium transition-colors duration-200',
            ]" v-show="shouldShowItem(item)">
              {{ item.name }}
            </router-link>
          </div>
        </div>

        <!-- User dropdown menu -->
        <div class="hidden sm:ml-6 sm:flex sm:items-center">
          <div class="relative">
            <button @click="toggleUserMenu" type="button"
              class="flex items-center rounded-full bg-indigo-100 text-indigo-800 hover:ring-2 hover:ring-indigo-500 hover:ring-offset-2 transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
              id="user-menu-button" :aria-expanded="showUserMenu" aria-haspopup="true">
              <span class="sr-only">Open user menu</span>
              <div class="h-9 w-9 rounded-full flex items-center justify-center text-sm font-semibold">
                {{ userInitials }}
              </div>
            </button>

            <!-- Dropdown menu -->
            <div v-if="showUserMenu"
              class="absolute right-0 z-20 mt-2 w-56 origin-top-right rounded-xl bg-white py-2 shadow-xl ring-1 ring-black ring-opacity-5 transform transition-all duration-300"
              :class="showUserMenu ? 'opacity-100 scale-100' : 'opacity-0 scale-95'" role="menu"
              aria-orientation="vertical" aria-labelledby="user-menu-button">
              <div class="px-4 py-2 text-sm text-gray-500 border-b border-gray-100">
                Signed in as <span class="font-semibold text-gray-700">{{ username }}</span>
              </div>
              <!-- Uncomment if profile page is needed -->
              <!-- <router-link
                to="/profile"
                class="block px-4 py-2 text-sm text-gray-700 hover:bg-indigo-50 hover:text-indigo-700"
                role="menuitem"
              >
                Your Profile
              </router-link> -->
              <button type="button" @click="handleLogout"
                class="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-indigo-50 hover:text-indigo-700"
                role="menuitem">
                Sign out
              </button>
            </div>
          </div>
        </div>

        <!-- Mobile menu button -->
        <div class="-mr-2 flex items-center sm:hidden">
          <button @click="toggleMobileMenu" type="button"
            class="inline-flex items-center justify-center rounded-lg p-2 text-gray-500 hover:bg-indigo-50 hover:text-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500"
            aria-controls="mobile-menu" :aria-expanded="showMobileMenu">
            <span class="sr-only">Open main menu</span>
            <Bars3Icon v-if="!showMobileMenu" class="h-6 w-6" aria-hidden="true" />
            <XMarkIcon v-else class="h-6 w-6" aria-hidden="true" />
          </button>
        </div>
      </div>
    </div>

    <!-- Mobile menu -->
    <div v-if="showMobileMenu" class="sm:hidden bg-white shadow-md" id="mobile-menu">
      <div class="space-y-1 pt-2 pb-3">
        <router-link v-for="item in navigationItems" :key="item.name" :to="item.href" :class="[
          isActive(item.href)
            ? 'bg-indigo-100 text-indigo-700'
            : 'text-gray-600 hover:bg-indigo-50 hover:text-indigo-700',
          'block px-4 py-3 rounded-md text-base font-medium transition-colors duration-200',
        ]" @click="toggleMobileMenu" v-show="shouldShowItem(item)">
          {{ item.name }}
        </router-link>
      </div>
      <div class="border-t border-gray-200 pt-4 pb-3">
        <div class="flex items-center px-4">
          <div class="flex-shrink-0">
            <div
              class="h-10 w-10 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-800 font-semibold">
              {{ userInitials }}
            </div>
          </div>
          <div class="ml-3">
            <div class="text-base font-medium text-gray-800">{{ username }}</div>
            <div class="text-sm font-medium text-gray-500">{{ userRole }}</div>
          </div>
        </div>
        <div class="mt-3 space-y-1">
          <!-- <router-link
            to="/profile"
            class="block px-4 py-2 text-base font-medium text-gray-500 hover:bg-indigo-50 hover:text-indigo-700"
            @click="toggleMobileMenu"
          >
            Your Profile
          </router-link> -->
          <button type="button" @click="handleLogout"
            class="block w-full text-left px-4 py-2 text-base font-medium text-gray-500 hover:bg-indigo-50 hover:text-indigo-700">
            Sign out
          </button>
        </div>
      </div>
    </div>
  </nav>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useAuthStore } from '../stores/auth'
import { Bars3Icon, XMarkIcon } from '@heroicons/vue/24/outline'
import logo from '../assets/ribbon-logo.svg' // Import the SVG logo

const router = useRouter()
const route = useRoute()
const authStore = useAuthStore()

// Navigation state
const showMobileMenu = ref(false)
const showUserMenu = ref(false)
const useFallbackLogo = ref(false) // For fallback logo

// Navigation items
const navigationItems = [
  { name: 'Dashboard', href: '/dashboard', requiresAuth: true },
  { name: 'Files', href: '/files', requiresAuth: true },
  { name: 'Search', href: '/search', requiresAuth: true },
  { name: 'Users', href: '/users', requiresAuth: true, requiresAdmin: true },
  { name: 'Presets', href: '/presets', requiresAuth: true, requiresAdmin: true },
]

// User information
const username = computed(() => authStore.user?.username || 'User')
const userRole = computed(() => authStore.user?.role || 'user')
const userInitials = computed(() => {
  const name = username.value
  return name.charAt(0).toUpperCase()
})

// Check if a path is the active route
const isActive = (path) => {
  if (route.path === path) return true
  return route.path.startsWith(path) && path !== '/'
}

// Check if a navigation item should be shown based on user permissions
const shouldShowItem = (item) => {
  if (item.requiresAuth && !authStore.isAuthenticated) return false
  if (item.requiresAdmin && (!authStore.user || authStore.user.role !== 'admin')) return false
  return true
}

// Toggle mobile menu
const toggleMobileMenu = () => {
  showMobileMenu.value = !showMobileMenu.value
  if (showMobileMenu.value) {
    showUserMenu.value = false
  }
}

// Toggle user menu
const toggleUserMenu = () => {
  showUserMenu.value = !showUserMenu.value
}

// Handle logout
const handleLogout = () => {
  authStore.logout()
  router.push('/login')
}
</script>

<style scoped>
/* Custom animations for dropdown and mobile menu */
@keyframes slideDown {
  from {
    opacity: 0;
    transform: translateY(-10px);
  }

  to {
    opacity: 1;
    transform: translateY(0);
  }
}

#mobile-menu {
  animation: slideDown 0.3s ease-out;
}
</style>

// frontend/src/components/Navbar.tsx
import React, { Fragment } from 'react';
import { Link, useLocation } from 'react-router-dom';
import { Menu, Transition } from '@headlessui/react';
import { UserIcon, Bars3Icon } from '@heroicons/react/24/outline';
import { useAuth } from '../context/AuthContext';

interface NavigationItem {
  name: string;
  href: string;
  requiresAdmin?: boolean;
}

const navigation: NavigationItem[] = [
  { name: 'Dashboard', href: '/dashboard' },
  { name: 'Files', href: '/files' },
  { name: 'Users', href: '/admin', requiresAdmin: true },
  { name: 'GDPR Search', href: '/gdpr-search' }
];

export const Navbar = () => {
  const { user, logout } = useAuth();
  const location = useLocation();
  
  const isCurrentPage = (href: string): boolean => location.pathname === href;
  
  const filteredNavigation = navigation.filter(
    item => !item.requiresAdmin || user?.role === 'admin'
  );

  return (
    <nav className="bg-white border-b border-gray-100">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex h-16 items-center justify-between">
          {/* Logo */}
          <Link 
            to="/" 
            className="text-xl font-medium text-gray-900 hover:text-gray-700 transition"
          >
            GDPR
          </Link>

          {/* Desktop Navigation */}
          <div className="hidden md:flex items-center gap-x-8">
            {filteredNavigation.map((item) => (
              <Link
                key={item.name}
                to={item.href}
                className={`text-sm transition-colors ${
                  isCurrentPage(item.href)
                    ? 'text-blue-600 font-medium'
                    : 'text-gray-600 hover:text-gray-900'
                }`}
              >
                {item.name}
              </Link>
            ))}

            {/* Profile Menu */}
            <Menu as="div" className="relative">
              <Menu.Button className="flex items-center">
                <UserIcon className="h-8 w-8 text-gray-600 hover:text-gray-900 transition p-1.5" />
              </Menu.Button>
              <Transition
                as={Fragment}
                enter="transition ease-out duration-100"
                enterFrom="transform opacity-0 scale-95"
                enterTo="transform opacity-100 scale-100"
                leave="transition ease-in duration-75"
                leaveFrom="transform opacity-100 scale-100"
                leaveTo="transform opacity-0 scale-95"
              >
                <Menu.Items className="absolute right-0 mt-2 w-48 rounded-lg bg-white py-2 shadow-lg ring-1 ring-gray-100">
                  <div className="px-4 py-2">
                    <p className="text-sm font-medium text-gray-900">{user?.username}</p>
                    <p className="text-xs text-gray-500">{user?.role}</p>
                  </div>
                  <div className="border-t border-gray-100 mt-2">
                    <Menu.Item>
                      {({ active }) => (
                        <button
                          onClick={logout}
                          className={`w-full text-left px-4 py-2 text-sm ${
                            active ? 'bg-gray-50 text-gray-900' : 'text-gray-600'
                          }`}
                        >
                          Sign out
                        </button>
                      )}
                    </Menu.Item>
                  </div>
                </Menu.Items>
              </Transition>
            </Menu>
          </div>

          {/* Mobile Menu Button */}
          <button className="md:hidden p-2 text-gray-600 hover:text-gray-900 transition">
            <Bars3Icon className="h-6 w-6" />
          </button>
        </div>
      </div>

      {/* Mobile Menu (hidden by default) */}
      <div className="hidden md:hidden border-t border-gray-100">
        <div className="px-4 py-3 space-y-3">
          {filteredNavigation.map((item) => (
            <Link
              key={item.name}
              to={item.href}
              className={`block text-sm ${
                isCurrentPage(item.href)
                  ? 'text-blue-600 font-medium'
                  : 'text-gray-600 hover:text-gray-900'
              }`}
            >
              {item.name}
            </Link>
          ))}
          <button
            onClick={logout}
            className="block w-full text-left text-sm text-gray-600 hover:text-gray-900 pt-3 border-t border-gray-100"
          >
            Sign out
          </button>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;
